group: travis_latest

jobs:
  include:

  - env:
    - DESCRIPTION="lua lint, test and docs deploy"
    - LUA="lua=5.1"
    stage: build
    language: python
    sudo: false
    branches:
      only:
        - master
    before_install:
      - pip install mkdocs mkdocs-material
      - make hererocks
    install:
      - make deps-lua
    script:
      - make lint
      - make test
      - make docs
    after_success:
      - make report-coveralls
    deploy:
      provider: pages
      fqdn: btk.bob.sh
      local-dir: site
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master


notifications:
  email: false

