group: travis_latest
git:
  depth: 3

jobs:
  include:

  - env:
    - DESCRIPTION="lua lint, test and docs deploy"
    - LUA="lua=5.1"
    stage: build
    language: python
    sudo: false
    branches:
      only:
        - master
    install:
      - make deps
    script:
      - make lint
      - make test
      - make docs
    after_success:
      - make report-coveralls
    deploy:
      provider: pages
      fqdn: btk.bob.sh
      local-dir: site
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master
    cache:
      pip: true
      directories:
      - lua_install # Cache our hererocks installs




notifications:
  email: false

