site_name: BTK
site_url: https://btk.bob.sh/
site_description: BTK Docs
site_author: Bob.sh Ltd
repo_name: bobsh/BTK
repo_url: https://github.com/bobsh/BTK
edit_uri: ""

copyright: 'Copyright &copy; 2018 Bob.sh Ltd'

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: 'Deep Purple'
    accent: 'Light Blue'
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.ico


pages:
  - Home: index.md
  - Development: development.md

extra:
  social:
    - type: 'github'
      link: 'https://github.com/bobsh'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences