site_name: BTK
site_url: https://bobsh.github.io/BTK/
site_description: BTK Docs
repo_name: bobsh/BTK
repo_url: https://github.com/bobsh/BTK

copyright: 'Copyright &copy; 2018 Bob.sh Ltd'

theme:
  name: material
  palette:
    primary: 'Deep Purple'
    accent: 'Light Blue'

pages:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Support: support.md
  - Development: development.md
  - 'API Reference': api.md

extra:
  social:
    - type: 'github'
      link: 'https://github.com/bobsh'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences