site_name: BTK
site_url: https://bobsh.github.io/BTK/
site_description: BTK Docs
repo_name: bobsh/BTK
repo_url: https://github.com/bobsh/BTK

theme: readthedocs

pages:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Support: support.md
  - Development: development.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true